
def convert_name_mlb_to_fangraphs(mlb_name):
    tbl = {"Washington Nationals": "Nationals",
           "Pittsburgh Pirates": "Pirates",
           "San Francisco Giants": "Giants",
           "Texas Rangers": "Rangers",
           "New York Yankees": "Yankees",
           "Toronto Blue Jays": "Blue Jays",
           "Arizona Diamondbacks": "Diamondbacks",
           "Houston Astros": "Astros",
           "Seattle Mariners": "Mariners",
           "Kansas City Royals": "Royals",
           "Chicago White Sox": "White Sox",
           "Miami Marlins": "Marlins",
           "Los Angeles Dodgers": "Dodgers",
           "St. Louis Cardinals": "Cardinals",
           "Atlanta Braves": "Braves",
           "Boston Red Sox": "Red Sox",
           "Cincinnati Reds": "Reds",
           "San Diego Padres": "Padres",
           "Cleveland Indians": "Indians",
           "Tampa Bay Rays": "Rays",
           "Baltimore Orioles": "Orioles",
           "Colorado Rockies": "Rockies",
           "Oakland Athletics": "Athletics",
           "Los Angeles Angels": "Angels",
           "Minnesota Twins": "Twins",
           "Detroit Tigers": "Tigers",
           "Philadelphia Phillies": "Phillies",
           "Milwaukee Brewers": "Brewers",
           "Chicago Cubs": "Cubs",
           "New York Mets": "Mets",
           }
    return tbl[mlb_name]

